import { makeStyles, Theme } from '@material-ui/core/styles';

export const useStyles = makeStyles((theme: Theme) => ({
    tableCell: {
        alignSelf: 'center',
        flexBasis: '6.63%!important',
        flexGrow: 1,
        flexShrink: 1,
        marginLeft: '0.75%',
        marginRight: '4.79%',
        minHeight: '20px',
        backgroundColor: 'rgba(0, 0, 0, 0)'
    },
    typography: {
        flexBasis: '100%',
        flexGrow: 0,
        flexShrink: 1,
        marginLeft: '0%',
        marginRight: '0%',
        marginTop: '0px',
        marginBottom: '0px',
        minWidth: '106px',
        color: 'rgba(61, 144, 227, 1)',
        fontSize: '14px!important',
        fontWeight: 400,
        fontFamily: 'Roboto',
        textAlign: 'left',
        lineHeight: '20px',
        letterSpacing: '0.25px'
    },
    tableCell1: {
        alignSelf: 'center',
        flexBasis: '7.38%!important',
        flexGrow: 1,
        flexShrink: 1,
        marginLeft: '4.79%',
        marginRight: '4.79%',
        minHeight: '20px',
        backgroundColor: 'rgba(0, 0, 0, 0)'
    },
    typography1: {
        flexBasis: '100%',
        flexGrow: 0,
        flexShrink: 1,
        marginLeft: '0%',
        marginRight: '0%',
        marginTop: '0px',
        marginBottom: '0px',
        minWidth: '118px',
        color: 'rgba(61, 144, 227, 1)',
        fontSize: '14px!important',
        fontWeight: 400,
        fontFamily: 'Roboto',
        textAlign: 'left',
        lineHeight: '20px',
        letterSpacing: '0.25px'
    },
    tableCell2: {
        alignSelf: 'center',
        flexBasis: '2.57%!important',
        flexGrow: 1,
        flexShrink: 1,
        marginLeft: '4.79%',
        marginRight: '4.79%',
        minHeight: '20px',
        backgroundColor: 'rgba(0, 0, 0, 0)'
    },
    typography2: {
        flexBasis: '100%',
        flexGrow: 0,
        flexShrink: 1,
        marginLeft: '0%',
        marginRight: '0%',
        marginTop: '0px',
        marginBottom: '0px',
        minWidth: '41px',
        color: 'rgba(30, 158, 143, 1)',
        fontSize: '14px!important',
        fontWeight: 400,
        fontFamily: 'Roboto',
        textAlign: 'left',
        lineHeight: '20px',
        letterSpacing: '0.25px'
    },
    tableCell3: {
        alignSelf: 'center',
        flexBasis: '0.63%!important',
        flexGrow: 1,
        flexShrink: 1,
        marginLeft: '4.79%',
        marginRight: '4.79%',
        minHeight: '20px',
        backgroundColor: 'rgba(0, 0, 0, 0)'
    },
    typography3: {
        flexBasis: '100%',
        flexGrow: 0,
        flexShrink: 1,
        marginLeft: '0%',
        marginRight: '0%',
        marginTop: '0px',
        marginBottom: '0px',
        minWidth: '10px',
        color: 'rgba(255, 255, 255, 1)',
        fontSize: '14px!important',
        fontWeight: 400,
        fontFamily: 'Roboto',
        textAlign: 'left',
        lineHeight: '20px',
        letterSpacing: '0.25px'
    },
    tableCell4: {
        alignSelf: 'center',
        flexBasis: '2.32%!important',
        flexGrow: 1,
        flexShrink: 1,
        marginLeft: '4.79%',
        marginRight: '4.79%',
        minHeight: '20px',
        backgroundColor: 'rgba(0, 0, 0, 0)'
    },
    typography4: {
        flexBasis: '100%',
        flexGrow: 0,
        flexShrink: 1,
        marginLeft: '0%',
        marginRight: '0%',
        marginTop: '0px',
        marginBottom: '0px',
        minWidth: '37px',
        color: 'rgba(255, 255, 255, 0.800000011920929)',
        fontSize: '14px!important',
        fontWeight: 400,
        fontFamily: 'Roboto',
        textAlign: 'left',
        lineHeight: '20px',
        letterSpacing: '0.25px'
    },
    tableCell5: {
        alignSelf: 'center',
        flexBasis: '2.94%!important',
        flexGrow: 1,
        flexShrink: 1,
        marginLeft: '4.79%',
        marginRight: '4.79%',
        minHeight: '20px',
        backgroundColor: 'rgba(0, 0, 0, 0)'
    },
    typography5: {
        flexBasis: '100%',
        flexGrow: 0,
        flexShrink: 1,
        marginLeft: '0%',
        marginRight: '0%',
        marginTop: '0px',
        marginBottom: '0px',
        minWidth: '47px',
        color: 'rgba(255, 255, 255, 1)',
        fontSize: '14px!important',
        fontWeight: 400,
        fontFamily: 'Roboto',
        textAlign: 'left',
        lineHeight: '20px',
        letterSpacing: '0.25px'
    },
    tableCell6: {
        alignSelf: 'center',
        flexBasis: '2%!important',
        flexGrow: 1,
        flexShrink: 1,
        marginLeft: '4.79%',
        marginRight: '4.79%',
        minHeight: '17px',
        backgroundColor: 'rgba(0, 0, 0, 0)'
    },
    typography6: {
        flexBasis: '100%',
        flexGrow: 0,
        flexShrink: 1,
        marginLeft: '0%',
        marginRight: '0%',
        marginTop: '0px',
        marginBottom: '0px',
        minWidth: '32px',
        color: 'rgba(255, 255, 255, 0.800000011920929)',
        fontSize: '14px!important',
        fontWeight: 400,
        fontFamily: 'Roboto',
        textAlign: 'left',
        lineHeight: '16.40625px',
        textTransform: 'capitalize'
    },
    tableCell7: {
        alignSelf: 'center',
        flexBasis: '1%!important',
        flexGrow: 1,
        flexShrink: 1,
        marginLeft: '4.79%',
        marginRight: '6.76%',
        minHeight: '17px',
        backgroundColor: 'rgba(0, 0, 0, 0)'
    },
    typography7: {
        flexBasis: '100%',
        flexGrow: 0,
        flexShrink: 1,
        marginLeft: '0%',
        marginRight: '0%',
        marginTop: '0px',
        marginBottom: '0px',
        minWidth: '16px',
        color: 'rgba(255, 255, 255, 0.800000011920929)',
        fontSize: '14px!important',
        fontWeight: 400,
        fontFamily: 'Roboto',
        textAlign: 'left',
        lineHeight: '16.40625px',
        textTransform: 'capitalize'
    },
    root: {
        minHeight: '44px',
        display: 'flex',
        flexDirection: 'row',
        justifyContent: 'space-between',
        alignItems: 'center',
        backgroundImage: 'url("data:image/svg+xml;base64,PHN2ZyBwcmVzZXJ2ZUFzcGVjdFJhdGlvPSJub25lIiB3aWR0aD0iMTU5OCIgaGVpZ2h0PSI0NCIgdmlld0JveD0iMCAwIDE1OTggNDQiIGZpbGw9Im5vbmUiIHhtbG5zPSJodHRwOi8vd3d3LnczLm9yZy8yMDAwL3N2ZyI+CjxyZWN0IHdpZHRoPSIxNTk4IiBoZWlnaHQ9IjQ0IiBmaWxsPSIjMUUyNDNBIi8+Cjwvc3ZnPgo=")',
        backgroundRepeat: 'no-repeat',
        backgroundSize: '100% 100%',
        backgroundPositionY: 'center',
        backgroundPositionX: 'center',
        backgroundColor: 'rgba(0, 0, 0, 0)'
    },
    root1: {
        height: '44px'
    },
    div: {
        minHeight: '20px',
        display: 'flex',
        alignItems: 'stretch',
        justifyContent: 'center'
    },
    div1: {
        minHeight: '17px',
        display: 'flex',
        alignItems: 'stretch',
        justifyContent: 'center'
    }
}));
