import { makeStyles, Theme } from '@material-ui/core/styles';

export const useStyles = makeStyles((theme: Theme) => ({
    list: {
        marginLeft: '0%',
        marginRight: '0%',
        marginTop: '56px',
        marginBottom: '11px',
        minHeight: '219px',
        display: 'flex',
        flexDirection: 'column',
        justifyContent: 'flex-start',
        backgroundColor: 'rgba(0, 0, 0, 0)'
    },
    typography: {
        marginLeft: '0%',
        marginRight: '0%',
        marginTop: '0px',
        marginBottom: '4px',
        minWidth: '376px',
        color: 'rgba(255, 255, 255, 1)',
        fontSize: '20px!important',
        fontWeight: 500,
        fontFamily: 'Roboto',
        textAlign: 'left',
        lineHeight: '23.4375px',
        letterSpacing: '0.15000000596046448px'
    },
    typography1: {
        marginLeft: '0%',
        marginRight: '46.31%',
        marginTop: '4px',
        marginBottom: '4px',
        minWidth: '201.8688507080078px',
        color: 'rgba(61, 144, 227, 1)',
        fontSize: '14px!important',
        fontWeight: 400,
        fontFamily: 'Roboto',
        textAlign: 'left',
        lineHeight: '20px',
        letterSpacing: '0.25px'
    },
    typography2: {
        marginLeft: '0%',
        marginRight: '50%',
        marginTop: '4px',
        marginBottom: '4px',
        minWidth: '188px',
        color: 'rgba(61, 144, 227, 1)',
        fontSize: '14px!important',
        fontWeight: 400,
        fontFamily: 'Roboto',
        textAlign: 'left',
        lineHeight: '20px',
        letterSpacing: '0.25px'
    },
    typography3: {
        marginLeft: '0%',
        marginRight: '51.64%',
        marginTop: '4px',
        marginBottom: '4px',
        minWidth: '181.83607482910156px',
        color: 'rgba(61, 144, 227, 1)',
        fontSize: '14px!important',
        fontWeight: 400,
        fontFamily: 'Roboto',
        textAlign: 'left',
        lineHeight: '20px',
        letterSpacing: '0.25px'
    },
    typography4: {
        marginLeft: '0%',
        marginRight: '41.8%',
        marginTop: '4px',
        marginBottom: '4px',
        minWidth: '218.81967163085938px',
        color: 'rgba(61, 144, 227, 1)',
        fontSize: '14px!important',
        fontWeight: 400,
        fontFamily: 'Roboto',
        textAlign: 'left',
        lineHeight: '20px',
        letterSpacing: '0.25px'
    },
    typography5: {
        marginLeft: '0%',
        marginRight: '56.97%',
        marginTop: '4px',
        marginBottom: '4px',
        minWidth: '161.80328369140625px',
        color: 'rgba(61, 144, 227, 1)',
        fontSize: '14px!important',
        fontWeight: 400,
        fontFamily: 'Roboto',
        textAlign: 'left',
        lineHeight: '20px',
        letterSpacing: '0.25px'
    },
    typography6: {
        marginLeft: '0%',
        marginRight: '53.28%',
        marginTop: '4px',
        marginBottom: '4px',
        minWidth: '175.67213439941406px',
        color: 'rgba(61, 144, 227, 1)',
        fontSize: '14px!important',
        fontWeight: 400,
        fontFamily: 'Roboto',
        textAlign: 'left',
        lineHeight: '20px',
        letterSpacing: '0.25px'
    },
    typography7: {
        marginLeft: '0%',
        marginRight: '43.44%',
        marginTop: '4px',
        marginBottom: '0px',
        minWidth: '212.65574645996094px',
        color: 'rgba(61, 144, 227, 1)',
        fontSize: '14px!important',
        fontWeight: 400,
        fontFamily: 'Roboto',
        textAlign: 'left',
        lineHeight: '20px',
        letterSpacing: '0.25px'
    },
    list1: {
        marginLeft: '0%',
        marginRight: '0%',
        marginTop: '11px',
        marginBottom: '64px',
        minHeight: '107px',
        display: 'flex',
        flexDirection: 'column',
        justifyContent: 'flex-start',
        backgroundColor: 'rgba(0, 0, 0, 0)'
    },
    typography8: {
        marginLeft: '0%',
        marginRight: '32.69%',
        marginTop: '4px',
        marginBottom: '4px',
        minWidth: '253.07691955566406px',
        color: 'rgba(61, 144, 227, 1)',
        fontSize: '14px!important',
        fontWeight: 400,
        fontFamily: 'Roboto',
        textAlign: 'left',
        lineHeight: '20px',
        letterSpacing: '0.25px'
    },
    typography9: {
        marginLeft: '0%',
        marginRight: '25.64%',
        marginTop: '4px',
        marginBottom: '4px',
        minWidth: '279.5897216796875px',
        color: 'rgba(61, 144, 227, 1)',
        fontSize: '14px!important',
        fontWeight: 400,
        fontFamily: 'Roboto',
        textAlign: 'left',
        lineHeight: '20px',
        letterSpacing: '0.25px'
    },
    typography10: {
        marginLeft: '0%',
        marginRight: '10.26%',
        marginTop: '4px',
        marginBottom: '0px',
        minWidth: '337.4358825683594px',
        color: 'rgba(61, 144, 227, 1)',
        fontSize: '14px!important',
        fontWeight: 400,
        fontFamily: 'Roboto',
        textAlign: 'left',
        lineHeight: '20px',
        letterSpacing: '0.25px'
    },
    root: {
        marginLeft: '0%',
        marginRight: '0%',
        marginTop: '12px',
        marginBottom: '28px',
        minHeight: '468px',
        display: 'flex',
        flexDirection: 'row',
        justifyContent: 'space-between',
        alignItems: 'center',
        backgroundImage: 'url("data:image/svg+xml;base64,PHN2ZyBwcmVzZXJ2ZUFzcGVjdFJhdGlvPSJub25lIiB3aWR0aD0iMTkyMCIgaGVpZ2h0PSI0NjgiIHZpZXdCb3g9IjAgMCAxOTIwIDQ2OCIgZmlsbD0ibm9uZSIgeG1sbnM9Imh0dHA6Ly93d3cudzMub3JnLzIwMDAvc3ZnIj4KPHBhdGggZmlsbC1ydWxlPSJldmVub2RkIiBjbGlwLXJ1bGU9ImV2ZW5vZGQiIGQ9Ik0wIDBIMTkyMFY0NjhIMEwwIDBaIiBmaWxsPSIjMjAyOTQwIi8+Cjwvc3ZnPgo=")',
        backgroundRepeat: 'no-repeat',
        backgroundSize: '100% 100%',
        backgroundPositionY: 'center',
        backgroundPositionX: 'center',
        backgroundColor: 'rgba(0, 0, 0, 0)'
    },
    div: {
        alignSelf: 'stretch',
        flex: 'auto',
        marginLeft: '8.33%',
        marginRight: '2%',
        minHeight: '468px',
        display: 'flex',
        flexDirection: 'column',
        justifyContent: 'flex-start'
    },
    div1: {
        alignSelf: 'stretch',
        flex: 'auto',
        marginLeft: '2%',
        marginRight: '2%',
        minHeight: '468px',
        display: 'flex',
        alignItems: 'stretch',
        justifyContent: 'center'
    },
    custom2517638: {
        flexBasis: '100%',
        flexGrow: 0,
        flexShrink: 1,
        marginLeft: '0%',
        marginRight: '0%',
        marginTop: '47px',
        marginBottom: '48px',
        minHeight: '373px'
    },
    div2: {
        alignSelf: 'stretch',
        flex: 'auto',
        marginLeft: '2%',
        marginRight: '2%',
        minHeight: '468px',
        display: 'flex',
        alignItems: 'flex-start',
        justifyContent: 'center'
    },
    custom2517626: {
        flexBasis: '100%',
        flexGrow: 0,
        flexShrink: 1,
        marginLeft: '0%',
        marginRight: 'auto',
        marginTop: '47px',
        marginBottom: '48px',
        minHeight: '373px'
    },
    div3: {
        alignSelf: 'stretch',
        flex: 'auto',
        marginLeft: '2%',
        marginRight: '8.33%',
        minHeight: '468px',
        display: 'flex',
        alignItems: 'flex-start',
        justifyContent: 'center'
    },
    custom2517614: {
        flexBasis: '99.96%',
        flexGrow: 0,
        flexShrink: 1,
        marginLeft: '0%',
        marginRight: 'auto',
        marginTop: '47px',
        marginBottom: '48px',
        minHeight: '373px'
    }
}));
