import { makeStyles, Theme } from '@material-ui/core/styles';

export const useStyles = makeStyles((theme: Theme) => ({
    tableCell: {
        alignSelf: 'center',
        flexBasis: '8.44%!important',
        flexGrow: 1,
        flexShrink: 1,
        marginLeft: '0.5%',
        marginRight: '1.28%',
        minHeight: '20px',
        backgroundColor: 'rgba(0, 0, 0, 0)'
    },
    typography: {
        flexBasis: '100%',
        flexGrow: 0,
        flexShrink: 1,
        marginLeft: '0%',
        marginRight: '0%',
        marginTop: '0px',
        marginBottom: '0px',
        minWidth: '135px',
        color: 'rgba(61, 144, 227, 1)',
        fontSize: '14px!important',
        fontWeight: 400,
        fontFamily: 'Roboto',
        textAlign: 'left',
        lineHeight: '20px',
        letterSpacing: '0.25px'
    },
    tableCell1: {
        alignSelf: 'center',
        flexBasis: '9.63%!important',
        flexGrow: 1,
        flexShrink: 1,
        marginLeft: '1.28%',
        marginRight: '1.63%',
        minHeight: '20px',
        backgroundColor: 'rgba(0, 0, 0, 0)'
    },
    typography1: {
        flexBasis: '100%',
        flexGrow: 0,
        flexShrink: 1,
        marginLeft: '0%',
        marginRight: '0%',
        marginTop: '0px',
        marginBottom: '0px',
        minWidth: '154px',
        color: 'rgba(61, 144, 227, 1)',
        fontSize: '14px!important',
        fontWeight: 400,
        fontFamily: 'Roboto',
        textAlign: 'left',
        lineHeight: '20px',
        letterSpacing: '0.25px'
    },
    tableCell2: {
        alignSelf: 'center',
        flexBasis: '3.31%!important',
        flexGrow: 1,
        flexShrink: 1,
        marginLeft: '1.63%',
        marginRight: '3.75%',
        minHeight: '20px',
        backgroundColor: 'rgba(0, 0, 0, 0)'
    },
    typography2: {
        flexBasis: '100%',
        flexGrow: 0,
        flexShrink: 1,
        marginLeft: '0%',
        marginRight: '0%',
        marginTop: '0px',
        marginBottom: '0px',
        minWidth: '53px',
        color: 'rgba(255, 255, 255, 1)',
        fontSize: '14px!important',
        fontWeight: 400,
        fontFamily: 'Roboto',
        textAlign: 'left',
        lineHeight: '20px',
        letterSpacing: '0.25px'
    },
    tableCell3: {
        alignSelf: 'center',
        flexBasis: '3.81%!important',
        flexGrow: 1,
        flexShrink: 1,
        marginLeft: '3.75%',
        marginRight: '2.66%',
        minHeight: '20px',
        backgroundColor: 'rgba(0, 0, 0, 0)'
    },
    typography3: {
        flexBasis: '100%',
        flexGrow: 0,
        flexShrink: 1,
        marginLeft: '0%',
        marginRight: '0%',
        marginTop: '0px',
        marginBottom: '0px',
        minWidth: '61px',
        color: 'rgba(255, 255, 255, 1)',
        fontSize: '14px!important',
        fontWeight: 400,
        fontFamily: 'Roboto',
        textAlign: 'left',
        lineHeight: '20px',
        letterSpacing: '0.25px'
    },
    tableCell4: {
        alignSelf: 'center',
        flexBasis: '3.81%!important',
        flexGrow: 1,
        flexShrink: 1,
        marginLeft: '3.28%',
        marginRight: '2.56%',
        minHeight: '20px',
        backgroundColor: 'rgba(0, 0, 0, 0)'
    },
    tableCell5: {
        alignSelf: 'center',
        flexBasis: '3.94%!important',
        flexGrow: 1,
        flexShrink: 1,
        marginLeft: '2.56%',
        marginRight: '3.66%',
        minHeight: '20px',
        backgroundColor: 'rgba(0, 0, 0, 0)'
    },
    typography4: {
        flexBasis: '100%',
        flexGrow: 0,
        flexShrink: 1,
        marginLeft: '0%',
        marginRight: '0%',
        marginTop: '0px',
        marginBottom: '0px',
        minWidth: '63px',
        color: 'rgba(255, 255, 255, 1)',
        fontSize: '14px!important',
        fontWeight: 400,
        fontFamily: 'Roboto',
        textAlign: 'left',
        lineHeight: '20px',
        letterSpacing: '0.25px'
    },
    tableCell6: {
        alignSelf: 'center',
        flexBasis: '3.94%!important',
        flexGrow: 1,
        flexShrink: 1,
        marginLeft: '3.66%',
        marginRight: '2.47%',
        minHeight: '20px',
        backgroundColor: 'rgba(0, 0, 0, 0)'
    },
    tableCell7: {
        alignSelf: 'center',
        flexBasis: '7.56%!important',
        flexGrow: 1,
        flexShrink: 1,
        marginLeft: '2.47%',
        marginRight: '0.84%',
        minHeight: '31px',
        backgroundColor: 'rgba(0, 0, 0, 0)'
    },
    typography5: {
        flexBasis: '30.58%',
        flexGrow: 0,
        flexShrink: 1,
        marginLeft: '5%',
        marginRight: '64%',
        marginTop: '6px',
        marginBottom: '5px',
        minWidth: '37px',
        color: 'rgba(255, 255, 255, 1)',
        fontSize: '14px!important',
        fontWeight: 400,
        fontFamily: 'Roboto',
        textAlign: 'left',
        lineHeight: '20px',
        letterSpacing: '0.25px'
    },
    tableCell8: {
        alignSelf: 'center',
        flexBasis: '3.13%!important',
        flexGrow: 1,
        flexShrink: 1,
        marginLeft: '0.84%',
        marginRight: '3.88%',
        minHeight: '20px',
        backgroundColor: 'rgba(0, 0, 0, 0)'
    },
    typography6: {
        flexBasis: '100%',
        flexGrow: 0,
        flexShrink: 1,
        marginLeft: '0%',
        marginRight: '0%',
        marginTop: '0px',
        marginBottom: '0px',
        minWidth: '50px',
        color: 'rgba(255, 255, 255, 1)',
        fontSize: '14px!important',
        fontWeight: 400,
        fontFamily: 'Roboto',
        textAlign: 'left',
        lineHeight: '20px',
        letterSpacing: '0.25px'
    },
    root: {
        minHeight: '44px',
        display: 'flex',
        flexDirection: 'row',
        justifyContent: 'space-between',
        alignItems: 'center',
        backgroundColor: 'rgba(0, 0, 0, 0)'
    },
    root1: {
        height: '44px'
    },
    div: {
        minHeight: '20px',
        display: 'flex',
        alignItems: 'stretch',
        justifyContent: 'center'
    },
    div1: {
        alignSelf: 'center',
        flexBasis: '3.81%!important',
        flexGrow: 1,
        flexShrink: 1,
        marginLeft: '2.66%',
        marginRight: '3.28%',
        minHeight: '20px',
        display: 'flex',
        alignItems: 'stretch',
        justifyContent: 'center',
        backgroundColor: 'rgba(0, 0, 0, 0)'
    },
    div2: {
        minHeight: '31px',
        display: 'flex',
        alignItems: 'flex-start',
        justifyContent: 'center'
    }
}));
