export enum SocketCode {
    GET_DELEGATE = 'GET_DELEGATE',
    GET_DELEGATES = 'GET_DELEGATES',
    GET_DELEGATES_INFO = 'GET_DELEGATES_INFO',

    ON_DELEGATES_INFO_UPDATE = 'ON_DELEGATES_INFO_UPDATE',
}
